---
title: "1.2_multiome_MM468"
author: "Anna Schwager"
date: "`r Sys.Date()`"
output: github_document
---

```{r silence, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE
)
```

Load the global variables 
```{r source, message=F, warning=F}
here::i_am("scripts/1.2_multiome_MM468.Rmd")
mainDir = here::here()
source(knitr::purl(file.path(mainDir,"scripts/global_variables.Rmd"), quiet=TRUE))
source(knitr::purl(file.path(mainDir, "scripts/functions.Rmd"), quiet=TRUE))

set.seed(123)
```


# Preparation and object creation
## Setting directories and input files
```{r input_dirs, message=F, warning=F}

inputDir_local = file.path(inputDir, "hg38", "MM468")
outputDir_local = file.path(outputDir, "1.2_multiome_MM468") ; if(!file.exists(outputDir_local)){dir.create(outputDir_local)}
outputDir_objects = file.path(outputDir_local, "objects") ; if(!file.exists(outputDir_objects)){dir.create(outputDir_objects)}
outputDir_plots = file.path(outputDir_local, "plots") ; if(!file.exists(outputDir_plots)){dir.create(outputDir_plots)}
outputDir_tables = file.path(outputDir_local, "tables") ; if(!file.exists(outputDir_tables)){dir.create(outputDir_tables)}


ld <- list.dirs(inputDir_local)
fragpaths <- list.files(ld[grepl("h3k27me3/.*fragmentFiles", ld)], full.names = TRUE)
fragpaths <- fragpaths[grepl('.tsv.gz$', list.files(ld[grepl("h3k27me3/.*fragmentFiles", ld)], full.names = TRUE))]
fragpaths <- fragpaths[grepl("one_cell_multiome", fragpaths)]
names(fragpaths) <- sub(".*MM468/([^/]+)/.*", "\\1", fragpaths)


rnapaths <- list.dirs(ld[grepl("/.*flash", ld)], full.names = TRUE)
rnapaths_umi <- unique(rnapaths[grepl("/.*10XlikeMatrix_umi$", rnapaths)])
rnapaths_fl <- unique(rnapaths[grepl("/.*10XlikeMatrix_read$", rnapaths)])

rnapaths <- list(rnapaths_umi, rnapaths_fl)
names(rnapaths) <- c("umi", "full_length")

rm(ld)

```

## Loading annotation
```{r annot, message=F, warning=F}
consensus_peaks_k27 <- toGRanges(file.path(annotDir, "MM468_peaks_h3k27me3.bed"), format="BED", header=FALSE)
```


## Loading the bulk bigwig
```{r bw_load, message=F, warning=F}
bw_bulk <- file.path(inputDir_local, "bigwigs", "MM468_ATCC_hu_WT_AM_m10y22_H3K27me3.bw")
```

#  Creating the object 
## RNA 
```{r create_object, message=F, warning=F, eval=F}

rna_seurat_list <- lapply(rnapaths, function(pathvec) {
  lapply(pathvec, function(p) {
    rna.data <- Read10X(data.dir = p)
    CreateSeuratObject(counts = rna.data,
                       min.cells = 1,
                       min.features = -1,
                       project = "mm468_multiome")
  })
})


rna_seurat_list <- lapply(rnapaths, function(p) {
    rna.data <- Read10X(data.dir = p)
    CreateSeuratObject(counts = rna.data,
                       min.cells = 1,
                       min.features = -1,
                       project = "mm468_multiome")
  })


```

## Epi
```{r objects, message=F, warning=F, eval=F}
seurat_list <- list()

for (i in names(fragpaths)){
    message(paste0("### Making fragment object for ", i))
    total_counts <- CountFragments(fragpaths[[i]])
    barcodes <- total_counts$CB
    frags <- CreateFragmentObject(path = fragpaths[[i]], cells = barcodes)
    
    message(paste0("### Making 50k bin matrix for ", i))
    bin50k_kmatrix = GenomeBinMatrix(
    frags,
    genome = hg38,
    cells = NULL,
    binsize = 50000,
    process_n = 10000,
    sep = c(":", "_"),
    verbose = TRUE)
    
    message(paste0("### Making peak matrix for ", i))
    peak_matrix = FeatureMatrix(
      frags,
      features = consensus_peaks_k27,
      cells = NULL,
      sep = c("-", "-"),
      verbose = TRUE)
    
    message(paste0("### Creating chromatin assay for ", i))
    chrom_assay <- CreateChromatinAssay(
      counts = bin50k_kmatrix,
      sep = c(":", "_"),
      genome = "hg38",
      fragments = fragpaths[[i]],
      min.cells = 1,
      min.features = -1)
    
    message(paste0("### Creating Seurat object for ", i))
    seurat <- CreateSeuratObject(
      counts = chrom_assay,
      assay = "bin_50k")
    
    seurat[["peaks"]] <- CreateChromatinAssay(
      counts = peak_matrix, genome = "hg38")
    
    Annotation(seurat) <- annotations_hg38
    
    seurat <- AddMetaData(seurat, CountFragments(fragpaths[[i]]))
    seurat <- FRiP(object = seurat, assay = "peaks", total.fragments = "frequency_count")
    
    message("### Adding RNA assays")
    seurat <- AddMetaData(seurat, rna_seurat_list[["umi"]]@meta.data)
    seurat[["RNA_umi"]] <- rna_seurat_list[["umi"]]@assays[["RNA"]]
    seurat$nCount_RNA_umi <- seurat$nCount_RNA
    seurat$nFeature_RNA_umi <- seurat$nFeature_RNA
    
    seurat <- AddMetaData(seurat, rna_seurat_list[["full_length"]]@meta.data)
    seurat[["RNA_fl"]] <- rna_seurat_list[["full_length"]]@assays[["RNA"]]
    seurat$nCount_RNA_fl <- seurat$nCount_RNA
    seurat$nFeature_RNA_fl <- seurat$nFeature_RNA
    
    seurat@meta.data[["orig.ident"]] <- i
    seurat_list[[i]] <- seurat
    
    
    rm(seurat)
    rm(frags)
    rm(total_counts)
    rm(barcodes)
    rm(fragments_per_cell)
    rm(bin50k_matrix)
    rm(peak_matrix)
    rm(chromatin_assay)
}

seurat <- seurat_list[["one_cell_multiome"]]
rm(seurat_list)
saveRDS(seurat, file.path(outputDir_objects, "seurat_MM468_h3k27me3_multiome.rds"))
 
```


```{r seurat_reload, message=F, warning=F}
seurat <- readRDS(file.path(outputDir_objects, "seurat_MM468_h3k27me3_multiome.rds"))
```


# QC
## Weighted histograms
```{r qc1, message=F, warning=F, fig.show="hold", out.width="50%"}

plot_weighted_hist(seurat) + ggtitle(print("H3k27me3"))
plot_weighted_hist(seurat, assay = "RNA_umi") + ggtitle(print("RNA_umi"))
plot_weighted_hist(seurat, assay = "RNA_fl") + ggtitle(print("RNA_fl"))

```

## Filtering

```{r merge_filter, message=F, warning=F}
min_reads_dna = 400
min_feature_rna = 400

seurat$filtering <- ifelse(seurat$frequency_count > min_reads_dna & seurat$nFeature_RNA_fl > min_feature_rna, 'pass', 'fail')
table(seurat@meta.data[["filtering"]])

```

Remove the cells not passing the filtering 
```{r subset1, message=F, warning=F}
seurat <- subset(seurat, subset = filtering == "pass")
```

# FrIP and N fragments plots
```{r qc4, message=F, warning=F, fig.show="hold", out.width="30%"}

p_frip <- VlnPlot(seurat, c("FRiP"), pt.size = 0) +
                  labs(title = "FRiP, MM468 multiome") +
                  stat_summary(fun.y = median, geom='point', size = 2, colour = "black", position = position_dodge(width = 0.9)) +
                  scale_fill_manual(values = c(mypal[3], mypal[2])) +
                  scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
                  theme(legend.position = "none")

p_count <- VlnPlot(seurat, c("frequency_count"), pt.size = 0) +
                   labs(title = "Unique DNA fragments\nper cell, MM468 multiome") +
                   stat_summary(fun.y = median, geom='point', size = 2, colour = "black", position = position_dodge(width = 0.9)) +
                   scale_fill_manual(values = c(mypal[3], mypal[2])) +
                   scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
                   theme(legend.position = "none")

p_count_rna_umi <- VlnPlot(seurat, c("nCount_RNA_umi"), pt.size = 0) +
                       labs(title = "Unique RNA UMI counts\nper cell, MM468 multiome") +
                       stat_summary(fun.y = median, geom='point', size = 2, colour = "black", position = position_dodge(width = 0.9)) +
                       scale_fill_manual(values = c(mypal[1], mypal[2])) +
                       scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
                       theme(legend.position = "none")

p_count_rna_fl <- VlnPlot(seurat, c("nCount_RNA_fl"), pt.size = 0) +
                       labs(title = "Unique RNA counts\nper cell, MM468 multiome") +
                       stat_summary(fun.y = median, geom='point', size = 2, colour = "black", position = position_dodge(width = 0.9)) +
                       scale_fill_manual(values = c(mypal[1], mypal[2])) +
                       scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
                       theme(legend.position = "none")

p_feature_rna_umi <- VlnPlot(seurat, c("nFeature_RNA_umi"), pt.size = 0) +
                       labs(title = "Unique RNA UMI features \nper cell, MM468 multiome") +
                       stat_summary(fun.y = median, geom='point', size = 2, colour = "black", position = position_dodge(width = 0.9)) +
                       scale_fill_manual(values = c(mypal[1], mypal[2])) +
                       scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
                       theme(legend.position = "none")

p_feature_rna_fl <- VlnPlot(seurat, c("nFeature_RNA_fl"), pt.size = 0) +
                       labs(title = "Unique RNA features\nper cell, MM468 multiome") +
                       stat_summary(fun.y = median, geom='point', size = 2, colour = "black", position = position_dodge(width = 0.9)) +
                       scale_fill_manual(values = c(mypal[1], mypal[2])) +
                       scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
                       theme(legend.position = "none")

p1 <- p_frip | p_count 
p2 <- p_count_rna_umi | p_feature_rna_umi 
p3 <- p_count_rna_fl | p_feature_rna_fl

#p1
#p2
#p3

```

## DNA to RNA reads scatter plots
```{r qc_scatter, message=F, warning=F, fig.show="hold", out.width="100%"}

meta <- seurat@meta.data

frags_to_rna_reads_fl <- ggplot(seurat@meta.data,
                             aes(x = frequency_count, y = nCount_RNA_fl)) +
                             geom_point(alpha = 1, stroke = 0, size = 2.5, color = mypal[3]) +  
                             labs(x = "N unique DNA fragments",
                                  y =  "N unique RNA reads, fl",
                                title = "N unique DNA fragments\n vs.\nN unique RNA reads, fl") +
                              coord_cartesian(xlim = c(0, NA), ylim = c(0, NA)) +
                              theme_classic() 

frags_to_genes_fl <- ggplot(seurat@meta.data,
                         aes(x = frequency_count, y = nFeature_RNA_fl, color = mark)) +
                             geom_point(alpha = 1, stroke = 0, size = 2.5, color = mypal[3]) +  
                             labs(x = "N unique DNA fragments",
                                  y =  "N unique genes, fl",
                                title = "N unique DNA fragments\n vs.\nN unique genes, fl") +
                                coord_cartesian(xlim = c(0, NA), ylim = c(0, NA)) +
                              theme_classic() 

frags_to_rna_reads_umi <- ggplot(seurat@meta.data,
                             aes(x = frequency_count, y = nCount_RNA_umi, color = mark)) +
                             geom_point(alpha = 1, stroke = 0, size = 2.5, color = mypal[3]) +  
                             labs(x = "N unique DNA fragments",
                                  y =  "N unique RNA reads, umi",
                                title = "N unique DNA fragments\n vs.\nN unique RNA reads, umi") +
                                coord_cartesian(xlim = c(0, NA), ylim = c(0, NA)) +
                              theme_classic() 

frags_to_genes_umi <- ggplot(seurat@meta.data,
                         aes(x = frequency_count, y = nFeature_RNA_umi, color = mark)) +
                             geom_point(alpha = 1, stroke = 0, size = 2.5, color = mypal[3]) +  
                             labs(x = "N unique DNA fragments",
                                  y =  "N unique genes, umi",
                                title = "N unique DNA fragments\n vs.\nN unique genes, umi") +
                                coord_cartesian(xlim = c(0, NA), ylim = c(0, NA)) +
                              theme_classic() 


p_scatter_fl <- frags_to_rna_reads_fl | frags_to_genes_fl
p_scatter_umi <- frags_to_rna_reads_umi | frags_to_genes_umi

p_scatters <- p_scatter_fl / p_scatter_umi

p_scatters
```

```{r save_scatter, message=F, warning=F, eval=F}
ggsave(file.path(outputDir_plots, "dna_rna_scatters.pdf"),
       plot = p_scatters,
       device = "pdf",
       units = "mm",
       width = 150,
       height = 145)
```


```{r qc_scatter_log, message=F, warning=F, fig.show="hold", out.width="100%"}

meta <- seurat@meta.data
frags_to_rna_reads_fl_log <- ggplot(seurat@meta.data,
                             aes(x = log10(frequency_count), y = log10(nCount_RNA_fl))) +
                             geom_point(alpha = 1, stroke = 0, size = 2.5, color = mypal[3]) +  
                             labs(x = "log10(unique DNA fragments)",
                                  y =  "log10(unique RNA reads)",
                                title = "N unique DNA fragments\n vs.\nN unique RNA reads, fl") +
                              coord_cartesian(xlim = c(0, NA), ylim = c(0, NA)) +
                              theme_classic() 

frags_to_genes_fl_log <- ggplot(seurat@meta.data,
                         aes(x = log10(frequency_count), y = nFeature_RNA_fl, color = mark)) +
                             geom_point(alpha = 1, stroke = 0, size = 2.5, color = mypal[3]) +  
                             labs(x = "log10(unique DNA fragments)",
                                  y =  "unique genes",
                                title = "N unique DNA fragments\n vs.\nN unique genes, fl") +
                                coord_cartesian(xlim = c(0, NA), ylim = c(0, NA)) +
                              theme_classic() 

frags_to_rna_reads_umi_log <- ggplot(seurat@meta.data,
                             aes(x = log10(frequency_count), y = log10(nCount_RNA_umi), color = mark)) +
                             geom_point(alpha = 1, stroke = 0, size = 2.5, color = mypal[3]) +  
                             labs(x = "log10(unique DNA fragments)",
                                  y =  "log10(unique RNA reads, UMI)",
                                title = "N unique DNA fragments\n vs.\nN unique RNA reads, UMI") +
                                coord_cartesian(xlim = c(0, NA), ylim = c(0, NA)) +
                              theme_classic() 

frags_to_genes_umi_log <- ggplot(seurat@meta.data,
                         aes(x = log10(frequency_count), y = nFeature_RNA_umi, color = mark)) +
                             geom_point(alpha = 1, stroke = 0, size = 2.5, color = mypal[3]) +  
                             labs(x = "log10(unique DNA fragments)",
                                  y =  "unique genes, UMI",
                                title = "N unique DNA fragments\n vs.\nN unique genes, UMI") +
                                coord_cartesian(xlim = c(0, NA), ylim = c(0, NA)) +
                              theme_classic() 


p_scatter_fl_log <- frags_to_rna_reads_fl_log | frags_to_genes_fl_log
p_scatter_umi_log <- frags_to_rna_reads_umi_log | frags_to_genes_umi_log

p_scatters_log <- p_scatter_fl_log / p_scatter_umi_log

p_scatters_log
```

```{r save_scatter_log, message=F, warning=F, eval=F}
ggsave(file.path(outputDir_plots, "dna_rna_scatters_log.pdf"),
       plot = p_scatters_log,
       device = "pdf",
       units = "mm",
       width = 120,
       height = 145)
```


# Coverage plots
```{r coverage_prep, message=F, warning=F}

max_cell <- subset(seurat,
                   subset = frequency_count == max(seurat@meta.data[["frequency_count"]]))

median(seurat@meta.data[["frequency_count"]])
#even number of observations

median_cell <- subset(seurat,
                   subset = frequency_count == median(seurat@meta.data[["frequency_count"]][-1])
                   )

```

```{r coverage_plot, message=F, warning=F}

roi = "chr5-600000-1400000"
coverage_pseudobulk <- CoveragePlot(
                         object = seurat,
                         region = roi,
                         window = 3000,
                         annotation = FALSE,
                         peaks = FALSE) 
coverage_pseudobulk[[1]][["scales"]][["scales"]][[2]] <-  scale_fill_manual(values = mypal[3])
coverage_pseudobulk[[1]][["data"]][["group"]] <- "pseudobulk"

coverage_max <- CoveragePlot(
                         object = max_cell,
                         window = 3000,
                         region = roi,
                         annotation = FALSE,
                         peaks = FALSE) 
coverage_max[[1]][["scales"]][["scales"]][[2]] <-  scale_fill_manual(values = mypal[3])
coverage_max[[1]][["data"]][["group"]] <- "max cell"

coverage_median <- CoveragePlot(
                         object = median_cell,
                         window = 3000,
                         region = roi,
                         annotation = FALSE,
                         peaks = FALSE) 
coverage_median[[1]][["scales"]][["scales"]][[2]] <-  scale_fill_manual(values = mypal[3])
coverage_median[[1]][["data"]][["group"]] <- "median cell"

coverage_bulk <- BigwigTrack(
                     bigwig = bw_bulk,
                     region = roi,
                     smooth = 3000,
                     type = "coverage",
                     y_label = "Normalised signal") +
                     scale_fill_manual(values = mypal[7]) +
                     theme(legend.position = "none") +
                     ggtitle("MM468 H3K27Me3 One Cell CUT&TAG")
coverage_bulk[["data"]][["bw"]] <- "bulk"

tile_plot <- TilePlot(object = seurat,
                        region = roi,
                        tile.cells = 25,
                        tile.size = 3000) + scale_fill_gradient(low = "white", high = "#005043")

gene_plot <- AnnotationPlot(object = seurat, region = roi)

p <- CombineTracks(
  plotlist = list(coverage_bulk, coverage_median, coverage_max, coverage_pseudobulk, tile_plot, gene_plot),
  heights = c(15,15,15,15,20,10)) & theme(axis.title.y = element_text(size = 7)) 

print(p)

```

```{r save3, message=F, warning=F, eval=FALSE}
ggsave(file.path(outputDir_plots, "tracks_onecell_cuttag_mm468_h3k27me3.pdf"),
       plot = p,
       device = "pdf",
       units = "mm",
       width = 250,
       height = 150)

ggsave(file.path(outputDir_plots, "bulk_track_mm468_h3k27me3.pdf"),
       plot = coverage_bulk,
       device = "pdf",
       units = "mm",
       width = 250,
       height = 50)

```



